// Phase 10 B — Generated by AppApprove. DO NOT EDIT BY HAND.
// Error-report helper used by entry.server.tsx's handleError hook +
// any worker-side try/catch. Posts to AppApprove with HMAC signing.

import type { AppLoadContext } from "@remix-run/cloudflare";

const APPAPPROVE_ENDPOINT =
  "https://appapprove.com/api/v1/error-report";

// Hard-coded at scaffold-generation time so the worker doesn't have
// to look it up — wrangler.toml + the deploy workflow already know
// which project this is.
const PROJECT_ID = "2ca57a99-d362-4c47-9996-d4d768af6aa2";

// Avoid feedback loops: if the customer Worker errors WHILE reporting,
// we drop the second error rather than spinning the loop.
let reportingNow = false;

export interface ReportableError {
  error: unknown;
  request?: Request;
  requestId?: string;
}

export async function reportError(
  context: AppLoadContext,
  input: ReportableError,
): Promise<void> {
  if (reportingNow) return;
  const env = context.cloudflare?.env as
    | { APP_APPROVE_PROJECT_SECRET?: string }
    | undefined;
  const secret = env?.APP_APPROVE_PROJECT_SECRET;
  if (!secret) return; // pre-Phase-10-B project; no-op until next deploy.

  const e = input.error;
  const errorClass =
    e instanceof Error
      ? (e.name || "Error")
      : typeof e === "object" && e !== null && "name" in e
        ? String((e as { name: unknown }).name ?? "Error")
        : "Error";
  const message =
    e instanceof Error
      ? e.message
      : typeof e === "string"
        ? e
        : JSON.stringify(e).slice(0, 2000);
  const stack = e instanceof Error ? (e.stack ?? null) : null;
  const route = input.request ? new URL(input.request.url).pathname : null;

  const payload = {
    projectId: PROJECT_ID,
    occurredAt: new Date().toISOString(),
    errorClass: errorClass.slice(0, 200),
    message: message.slice(0, 2000),
    stack: stack ? stack.slice(0, 20_000) : null,
    route,
    requestId: input.requestId ?? null,
  };
  const body = JSON.stringify(payload);

  try {
    reportingNow = true;
    const signature = await hmacHex(secret, body);
    await fetch(APPAPPROVE_ENDPOINT, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-appapprove-signature": signature,
      },
      body,
      // 5s timeout — error reporting must not block the request response.
      signal: AbortSignal.timeout(5_000),
    });
  } catch {
    // Fail-open. We never want error reporting to break the live app.
  } finally {
    reportingNow = false;
  }
}

async function hmacHex(secret: string, body: string): Promise<string> {
  // Workers crypto.subtle — same algorithm as
  // lib/health-monitor/project-secret.ts on the landing side.
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(body),
  );
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
